name: Publish Gradle Plugin to Graple Plugin Portal

on:
  workflow_dispatch:

jobs:
  publish-gradle-plugin:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Publish
      run: ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
