name: Build IDE plugin and create a GitHub Release

on:
  workflow_dispatch:

jobs:
  publish-ide-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build plugin
        run: ./gradlew buildKelpIdePlugin readVersion

      - name: Fetch plugin version
        id: print_version
        run: echo "plugin-version=$(cat build/VERSION)" >> $GITHUB_OUTPUT

      - name: Release plugin
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.print_version.outputs.plugin-version }}
          artifacts: "./build/github-release/*"
          body: "TODO"
          draft: true
